[air]
  root = "."
  testdata_dir = "testdata"
  tmp_dir = "tmp"
  
  [build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/grpc/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "pkg/proto","gen"]
  exclude_file = []
  exclude_regex = ["_test.go", "\\.pb\\.go$", "\\.pb\\.gw\\.go$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal"]
  include_ext = ["go", "proto"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = ["task sqlc"]
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_root = false
  
  [color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
  
  [air.log]
    main_only = false
    time = false

  [air.misc]
    clean_on_exit = true

  [air.screen]
    clear_on_rebuild = true
    keep_scroll = false
